---
resources:
- name: concourse-tutorial
  type: git
  source:
    uri: https://github.com/myminseok/concourse-tutorial.git
    branch: master

jobs:
- name: job-hello-world
  public: false
  plan:
  - aggregate:
    - get: concourse-tutorial
  - task: hello-world
    file: concourse-tutorial/tutorials/mkim-input/test-task.yml
    params:
      TEST: ((test))
    input_mapping:
      concourse-test-files: concourse-tutorial
      
